[package]
name = "day10"
version = "0.1.0"
authors = ["Matt Whelan <matt@blacklogik.com>"]
edition = "2021"

[dependencies]
regex = "1"
itertools = "0.10"
anyhow = "1.0.44"
thiserror = "1.0.30"
lazy_static = "1.4.0"
